sudo: required
dist: trusty

language: cpp

compiler:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cmake
  - sudo apt-get install -qq libboost-all-dev

before_script:
  - mkdir _build
  - cd _build
  - cmake ..

script: make